
const data = {

    keywords:[

        "none",
 
        "genre", 
        "theme",
        "adject",
        "genreAdject",
        "create",
        "think",

        "bigCat",
        "medCat",
        "miniCat",

        "specialCat",
        "media",
        "theming",

        "character",
        "tool",
        "action",

        "place",
        "placeAdject",
        "placeUnique",
        "placeStart",

        "focusing",

    ],

    mainStruct:[ 
        "@create# @adject# @genre# @theming#",
        "@create# @specialCat# @genre# @theming#",
        "@create# @genre#... except it's also a @genre#!",
        "invent a new genre, a @adject#@media# @think# @bigCat#", 
    ],

    subStruct:[
        "an excuse to make @miniCat#",
        "initially about $allThemes#s but then $allThemes#s!", 
        "@placeStart# $manyMaybePlaces#... @action# the $allThemes#!",
        "$manyMaybePlaces# invaded by $charMaybePlural#!",
        "everything should be @adject#!",
    ],

    detailStruct:[  
        "the @medCat# is @miniCat#!",
        "@bigCat# focuses on $allThemes#s", 
        "choose between @tool#, @tool# and @tool#!",
        "@focusing# $allCats#", 
        "@placeStart# $manyMaybePlaces",
    ], 

    correction:[
        ["ultramans","ultramen"], 
        ["city","cities"],
    ],

    packages:{ 
         charMaybePlural:["$pronounSingular# $maybeAdject#@character#","$pronounPlural# $maybeAdject#@character#s"],
         manyMaybePlaces:["$pronounSingular# $maybePlaceAdject#@place#","$pronounPlural# $maybePlaceAdject#@place#s","$pronounSingular# $maybePlaceAdject#@place#","$pronounPlural# $maybePlaceAdject#@place#s","@placeUnique#"],
         maybePlaceAdject:["","@adject#","@placeAdject#"],
         maybeAdject:["","@adject#"],
         placeAndUnique:["@place#","@place#","@placeUnique#"],
         allThemes:["@character#","@tool#","@place#"],
         allCats:["@bigCat#","@medCat#","@miniCat#"],
         bigAndSmall:["@bigCat#","@miniCat#"],
         bigAndMed:["@bigCat#","@medCat#"],
         smallAndMed:["@miniCat#","@medCat#"],
         pronounPlural:["","","the","the","our","your","many","countless","infinite"],
         pronounSingular:["a","a","the","the","your"],
    },

    videogame:{

        none:[""],


        focusing:["brainstorm the","find a different way to do","avoid","Basically just","Focus on","No matter what, don't put in","Consider adding","Gameplay revolves around","With basic-ass","Use an original way to do"],


        placeStart:[
            "",
            "",
            "",
            "in ",
            "explore ",
            "travel to ",
            "conquest of ",
            "build your home in ",
            "make your home in ",
            "go to ",
            "escape from ",
            "everything is in ",
            "visit ",
            "road to ",
            "finally leave ",
        ],
 
        create:[
            "craft a",
            "handmake a",
            "the minimalist",
            "a rough, messy",
            "reinvent the",
            "an insult to the genre of",
            "A version you'd hate of",
            "a clone of your favorite",
            "a parody",
        ],

        theming:[
            "about $allThemes#s",
            "about a $allThemes#",
            "about... $allThemes#s!",
            "about making $allThemes#s",
            "with theme: $allThemes#s",
            "about fighting $charMaybePlural#",
            "starring a @character#",
            "starring @character#s",
            "secretly about  $allThemes#s",
            "about collecting  $allThemes#s",
        ],

        media:[
            "game",
            "game",
            "game",
            "game",
            "competitive game",
            "MMO",
            "puzzler",
            "toy",
            "storygame"
        ],

        think:[
            "rethinking",
            "focusing on",
            "with no",
        ], 
        

        genre: [
            "topdown @genre#",
            "sidescrolling @genre#",
            "autobattler",
            "platformer",
            "jrpg",
            "soulslike",
            "beat'em up",
            "fighting game",
            "shmup", 
            "pseudoboardgame",
            "monster collecter",
            "creature raising sim",
            "detective game",
            "dungeon crawler",
            "classic roguelike",
            "crazy taxi",
            "building game", 
            "citybuilder",
            "deckbuilder",
            "beautiful explorable world",
            "idle game",
            "shared persistent world",
        ],
        
        specialCat:[
            "",
            "unclear-if-coop",
            "endlessly looping",
            "super-short",
            "story-based",
            "roguelite",
            "rpg-elements",
            "co-op",
            "competitive",
            "assymetric-multiplayer",
            "run-based",
            "randomly generated",
        ],

        bigCat: [
            "chara creation",
            "combat",
            "exploration",
            "dialogue",
            "worldbuild-sim",
            "loadout-powerups",
            "party-building",
            "inventory",
        ],

        medCat: [
            "class-change",
            "heat actions",
            "headshots",
            "critical hits",
            "cooking",
            "monsterhunter-style grind",
            "special super attacks",
            "no-recipe mixing",
            "unclear openworld",
            "branching evolutions",
            "robot assembly",
            "party building",
            "card deck equivalent",
            "parrying",
            "chara customization",
            "too many weapons",
            "farming / building",
            "roguelite element",
            "procedural levels",
            "metro-idvania progression"
        ],

        miniCat:[
            "treasure",
            "crafting",
            "healing",
            "npcs",
            "hit points",
            "bosses",
            "cards",
            "weapons",
            "equipment",
            "romances",
            "super moves",
            "monsters",
            "other players",
            "rpg stats",
        ],

        character: [
            "aardvark",
            "ookapi",
            "ultraman",
            "electric eel",
            "albatross",
            "baboon",
            "gorilla",
            "monkey",
            "cat",
            "orangutan",
            "robot",
            "giant robot",
            "dark lord",
            "demon",
            "anime maid",
            "primordial beast",
            "animal",
            "giant",
            "boyfriend",
            "girlfriend",
            "bride",
        ],

        theme: [
            "baboon",
            "gorilla",
            "monkey",
            "cat",
            "orangutan",
            "robot",
            "hell",
            "demon",  
        ],

        genreAdject: [
            "nonrandom ", 
            "randomly generated ",
            "boss ",
            "final boss ", 
        ],

        adject:[ 
            "@genreAdject#",
            "@genreAdject#",
            "sci-@adject#",
            "sci-",
            "kawaii ",
            "shining ",
            "burning ",
            "loathsome ",
            "wretched ",
            "accursed ",
            "legendary ",
            "dream ",
            "horror ",
            "spooky ",
            "spicy ", 
            "bug ",
            "bone ",
            "blood ",
            "combining ",
            "transforming ",
            "communist ",
            "just ",
            "divine ",
            "undead ",
            "powerful ",
            "friendly ",
            "goofy ",
            "exaggerated ",
            "cyborg ",
            "cyber",
            "mecha",
            "robo",
            "world-destroying ",
            "eco-friendly ",
            "romantic ",
            "giga",
            "giga-banana ",
            "super auto ",
            "giant ",
        ],

        action:[
            "find",
            "destroy",
            "purify",
            "grow",
            "evolve",
            "equip",
            "upgrade"
        ],

        tool:[
             "drill",
             "big sword", 
             "frozen tuna",
             "bone-in-meat",
             "firebreath",
             "pincer",
             "huge robot arm",
             "mallet",
             "maid dress",
             "claw",
             "fang",
             "tree trunk",
             "shotgun",
             "wave cannon",
             "gatling gun",
             "hand",
             "fist",
             "frog",
             "laser",
             "laser @tool#",
             "spiked club",
             "flame",
             "horns",
             "melon",
             "curse",
             "bugs", 
             "boomerang",
             "cat",
             "crab",
             "heavenly lightning",
             "stardust",
             "monster transformation",
             "scimitar",
             "real japanese katana",
             "ultra greatsword",
             "robot suit",
             "cactus",
             "alien parasite",
             "anti-tank rifle",
             "centipede",
             "muscle body",
        ],

        placeAdject:[
            "hallowed ",
            "ruined ",
            "cursed ",
            "vast ",
            "deep ",
            "endless ",

        ],

        place:[
             "earth",
             "world tree", 
             "castle",
             "great lake",
             "savannah",
             "jungle",
             "cave",
             "forest", 
             "temple",
             "planet",
             "galaxy",
             "@adject#zone", 
             "night club",
             "social media",
             "skeleton world",
             "capital",
             "hell",
             "heck",
             "buttfuck nowhere",
             "big mountain",
             "sea",
             "underground city",
             "ancient babylon",
        ],

        placeUnique:[
            "a large mall",
            "the ocean",
            "planet X",
            "the dark recesses of the mind",
            "montreal",
            "tokyo",
            "neo kobe city",
            "new neo new york",
        ]
 

    },
    none:1,
    genre: 17,

    bigCat: 8,
    medCat: 8,
    miniCat: 8,

    specialCat:10,
    
    adject: 31,
    genreAdject: 1,
    create: 8,
    think: 3,
    media:4,
    theme:8,
    theming:8, 

    place:8,
    character:8,
    tool:8,
}

export default data